### ISSUE TITLE
Support for Mac OSX

### ISSUE THREAD

**Issue by rohitjoshi** [logcabin/logcabin#131]
When I compile on mac-osx with gnu 4.9 compiler, getting error related to sys/epoll.h

    build/RPC/ClientSession.cc:19:23: fatal error: sys/epoll.h: No such file or directory
     #include <sys/epoll.h>

**Comment by ongardie** [comment]
LogCabin currently uses a few Linux-only features, such as epoll. Do you have a VM or server you can use instead?

**Comment by rohitjoshi** [comment]
@ongardie I am planning to integrate LogCabin to add clustering support in [LightQ](https://github.com/LightIO/LightQ).  I am using MacOSX as my development environment but may be switch to Linux for LogCabin integration.

Do you have any plan to support MacOSX?

**Comment by ongardie** [comment]
@rohitjoshi, sorry for the delay. Integration with LightQ would be cool; let me know if you want to chat more about that.

There's no current plans to support Mac OS X, sorry. I'd welcome patches for it, with two caveats:

1. It might be a significant undertaking. I don't know how many Linux-only features have crept into LogCabin over time, and I'm not very familiar with differences between Linux and OS X.
2. I'm not sure I could keep the OS X stuff working, as I don't currently have OS X to test with. It does look like Travis CI can support OS X, but currently they've turned off the ability for people to use both that and Linux: http://docs.travis-ci.com/user/multi-os/

**Comment by coruus** [comment]
Another problem is OSX's irritating failure to support POSIX's clock_gettime.

So: This is the logic that Python now uses to implement a [cross-platform monotonic clock](https://www.python.org/dev/peps/pep-0418/):

```python
if os.name == 'nt':
    # . . .
elif sys.platform == 'darwin':
    def monotonic():
        if monotonic.factor is None:
            factor = _time.mach_timebase_info()
            monotonic.factor = timebase[0] / timebase[1] * 1e-9
        return _time.mach_absolute_time() * monotonic.factor
    monotonic.factor = None
elif hasattr(time, "clock_gettime") and hasattr(time, "CLOCK_HIGHRES"):
    def monotonic():
        return time.clock_gettime(time.CLOCK_HIGHRES)
elif hasattr(time, "clock_gettime") and hasattr(time, "CLOCK_MONOTONIC"):
    def monotonic():
        return time.clock_gettime(time.CLOCK_MONOTONIC)
```

I don't think that 64-bit IEEE754 is, in general, sufficient to ensure as-if-infinite-precision round-to-nearest using this approach. There is some analysis here, which is neither obviously correct nor incorrect (for me at least): http://stackoverflow.com/questions/23378063/how-can-i-use-mach-absolute-time-without-overflowing
but if you care about ensuring correct rounding, I can try to use [Sollya](http://sollya.gforge.inria.fr/) and [Gappa](http://gappa.gforge.inria.fr/) to verify.

Or is this way too picky? (Simpler is probably just to use `long doubles` on AMD64, which is good enough.)

**Comment by ongardie** [comment]
That's good info, @coruus, but I wouldn't waste your time on it unless someone creates an OS X-compatible event loop first, which I assume will be more difficult.

**Comment by rohitjoshi** [comment]
@ongardie Given the complexity involved, it's OK if LogCabin is not supported on the OSX platform.  Production environment for  [LightQ](https://github.com/LightIO/LightQ) would be Linux so I will try to use #ifdef linux to add  cluster support using LogCabin.

Thanks
