### PR TITLE
Fix build: missing unistd.h include

### PR DESCRIPTION
**Pull request by stevenjohnstone**
Got this error:
```
Compiling build/Storage/SnapshotFile.cc
build/Storage/SnapshotFile.cc: In member function ‘void LogCabin::Storage::SnapshotFile::Writer::seekToEnd()’:
build/Storage/SnapshotFile.cc:175:45: error: ‘lseek64’ was not declared in this scope
     off64_t r = lseek64(file.fd, 0, SEEK_END);
```

Building on debian jessie
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie
```

### CODE REVIEW

**Comment by ongardie** [comment]
Thanks. I usually develop on Debian jessie too but with g++ 4.4 (the oldest compiler LogCabin supports), and sometimes the newer compilers are more strict. I'm running builds on gcc 4.4, 4.5, 4.6, 4.7, 4.8, and 4.9 now to make sure nothing else is broken.

**Comment by ongardie** [comment]
g++-4.9 complained about a dead function (4ff2a964), but things now seem ok on g++ 4.4 through 4.9.

**Comment by stevenjohnstone** [comment]
Got the same here (although it was a warning). Pulled your change; builds cleanly now. Thanks!
